import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Reel Pipeline Terms of Service — service description, user responsibilities, third-party platforms, content ownership, and usage terms.",
};

export default function TermsPage() {
  return (
    <>
      {/* Header */}
      <section
        style={{
          position: "relative",
          overflow: "hidden",
          paddingTop: "5rem",
          paddingBottom: "3rem",
        }}
      >
        <div className="container-narrow" style={{ position: "relative" }}>
          <div className="animate-fade-in-up">
            <div className="badge" style={{ marginBottom: "1.5rem" }}>
              Legal
            </div>
            <h1 className="heading-xl" style={{ marginBottom: "1rem" }}>
              Terms of Service
            </h1>
            <p className="body-sm">
              Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="section-spacing" style={{ paddingTop: "2rem" }}>
        <div className="container-narrow legal-content">
          <div className="animate-fade-in-up">
            <p className="body-lg" style={{ marginBottom: "2rem" }}>
              These Terms of Service (&quot;Terms&quot;) govern your use of
              Reel Pipeline (&quot;the Service&quot;). By using the Service,
              you agree to these Terms. If you do not agree, do not use the
              Service.
            </p>

            <h2>1. Service Description</h2>
            <p>
              Reel Pipeline is an automated short-form video creation and
              social media publishing service. The Service generates video
              reels from user-managed content and can publish them to
              authorized social media accounts on Facebook, Instagram, and
              TikTok through their official APIs.
            </p>
            <p>
              The Service operates as a content production and publishing
              pipeline. It does not host or publicly distribute content on
              its own — publishing occurs only to accounts that the user has
              explicitly authorized.
            </p>

            <h2>2. Acceptance</h2>
            <p>
              By accessing or using the Service, you confirm that you accept
              these Terms and agree to comply with them. You also confirm
              that you have the legal capacity to enter into these Terms.
            </p>

            <h2>3. User Responsibilities</h2>
            <p>As a user of the Service, you are responsible for:</p>
            <ul>
              <li>
                Ensuring that all content you provide for video generation
                (quotes, text, metadata) does not infringe on the
                intellectual property rights of others.
              </li>
              <li>
                Maintaining the security of your social media account
                credentials and authorizations.
              </li>
              <li>
                Complying with the terms of service and community guidelines
                of each social media platform you publish to (Facebook,
                Instagram, TikTok).
              </li>
              <li>
                Reviewing generated content before confirming publication to
                your social media accounts.
              </li>
              <li>
                Providing accurate information when contacting us or
                configuring the Service.
              </li>
            </ul>

            <h2>4. Account Security</h2>
            <ul>
              <li>
                You are responsible for safeguarding the credentials used to
                access the Service and for any activity under your accounts.
              </li>
              <li>
                OAuth tokens stored by the Service are used exclusively for
                their intended publishing purpose and are not shared with
                third parties.
              </li>
              <li>
                You may revoke platform authorizations at any time through
                the respective platform&apos;s settings (e.g., TikTok app
                permissions, Facebook app settings).
              </li>
            </ul>

            <h2>5. User Content and Ownership</h2>
            <ul>
              <li>
                You retain ownership of the content you provide for video
                generation (quotes, text).
              </li>
              <li>
                Videos generated by the Service are created from your
                content combined with third-party media (Pexels video,
                Jamendo music) that is sourced under their respective
                licenses.
              </li>
              <li>
                You are responsible for ensuring that your use of generated
                videos complies with the licensing terms of the media
                providers used (Pexels, Jamendo, Microsoft Edge TTS).
              </li>
              <li>
                Content published to social media platforms is subject to
                the terms and policies of those platforms.
              </li>
            </ul>

            <h2>6. Prohibited Use</h2>
            <p>You must not use the Service to:</p>
            <ul>
              <li>
                Generate or publish content that is illegal, harmful,
                threatening, abusive, harassing, defamatory, or otherwise
                objectionable.
              </li>
              <li>
                Infringe on intellectual property rights, trademarks, or
                copyrights of others.
              </li>
              <li>
                Attempt to bypass platform API restrictions, rate limits, or
                review requirements.
              </li>
              <li>
                Use the Service for spam, bulk unsolicited publishing, or
                misleading content.
              </li>
              <li>
                Reverse-engineer, modify, or redistribute the Service
                without authorization.
              </li>
            </ul>

            <h2>7. Third-Party Platforms</h2>
            <p>
              The Service integrates with third-party social media platforms
              (Facebook, Instagram, TikTok). Your use of these platforms
              through the Service is also subject to their respective terms
              of service:
            </p>
            <ul>
              <li>
                <a
                  href="https://www.facebook.com/terms"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "var(--accent-primary)" }}
                >
                  Facebook Terms of Service
                </a>
              </li>
              <li>
                <a
                  href="https://help.instagram.com/581066165581870"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "var(--accent-primary)" }}
                >
                  Instagram Terms of Use
                </a>
              </li>
              <li>
                <a
                  href="https://www.tiktok.com/legal/terms-of-service"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "var(--accent-primary)" }}
                >
                  TikTok Terms of Service
                </a>
              </li>
            </ul>
            <p>
              We are not responsible for the availability, changes, or
              policies of third-party platforms. Publishing capabilities may
              be affected by platform API changes, review requirements, or
              account-level restrictions outside our control.
            </p>

            <h2>8. TikTok Integration</h2>
            <p>
              The TikTok integration uses TikTok&apos;s Content Posting API.
              Important notes:
            </p>
            <ul>
              <li>
                Reel Pipeline is not affiliated with, endorsed by, or
                officially partnered with TikTok or ByteDance Ltd.
              </li>
              <li>
                TikTok publishing capabilities are subject to TikTok&apos;s App
                Review process and approval status.
              </li>
              <li>
                The Service requests only the minimum permissions necessary
                for video publishing (video.upload, video.publish).
              </li>
              <li>
                Users can revoke TikTok authorization at any time through
                their TikTok account settings.
              </li>
            </ul>

            <h2>9. Service Availability</h2>
            <p>
              The Service is provided on an &quot;as available&quot; basis.
              We do not guarantee uninterrupted access or availability.
              Service interruptions may occur due to maintenance, updates,
              third-party API changes, or other factors.
            </p>

            <h2>10. Intellectual Property</h2>
            <p>
              The Service software, design, documentation, and branding are
              the intellectual property of Reel Pipeline. This does not
              affect your ownership of the content you provide or the
              licensing terms of third-party media used in video generation.
            </p>

            <h2>11. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, the Service
              is provided &quot;as is&quot; without warranty of any kind. We
              are not liable for:
            </p>
            <ul>
              <li>
                Failures in video generation or publishing caused by
                third-party API changes or outages.
              </li>
              <li>
                Content that violates platform community guidelines or
                policies after being published.
              </li>
              <li>
                Loss of data, tokens, or account access due to factors
                outside our control.
              </li>
              <li>
                Any indirect, incidental, or consequential damages arising
                from use of the Service.
              </li>
            </ul>

            <h2>12. Termination</h2>
            <ul>
              <li>
                You may stop using the Service at any time by revoking
                platform authorizations and discontinuing use.
              </li>
              <li>
                We may suspend or terminate access to the Service if these
                Terms are violated or if continued operation poses a risk.
              </li>
              <li>
                Upon termination, your stored OAuth tokens will be deleted.
                Content you have published to social media platforms will
                remain on those platforms subject to their own policies.
              </li>
            </ul>

            <h2>13. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Changes will be
              posted on this page with an updated date. Continued use of the
              Service after changes constitutes acceptance of the revised
              Terms.
            </p>

            <h2>14. Contact</h2>
            <p>
              For questions about these Terms, please use our{" "}
              <Link
                href="/contact"
                style={{ color: "var(--accent-primary)" }}
              >
                contact form
              </Link>
              .
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
